// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Detail: typeof import('./src/components/user/detail.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTree: typeof import('element-plus/es')['ElTree']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpForm: typeof import('./src/components/simp/SimpForm.vue')['default']
    SimpList: typeof import('./src/components/simp/SimpList.vue')['default']
    SimpMenu: typeof import('./src/components/simp/SimpMenu.vue')['default']
    SimpSearch: typeof import('./src/components/simp/SimpSearch.vue')['default']
    SimpTree: typeof import('./src/components/simp/SimpTree.vue')['default']
    TenantBasicInfo: typeof import('./src/components/tenant/TenantBasicInfo.vue')['default']
    TenantDetail: typeof import('./src/components/tenant/TenantDetail.vue')['default']
    TenantFuncAdd: typeof import('./src/components/tenant/TenantFuncAdd.vue')['default']
    TenantFuncInfo: typeof import('./src/components/tenant/TenantFuncInfo.vue')['default']
    TenantUserAdd: typeof import('./src/components/tenant/TenantUserAdd.vue')['default']
    TenantUserAuth: typeof import('./src/components/tenant/TenantUserAuth.vue')['default']
    TenantUserInfo: typeof import('./src/components/tenant/TenantUserInfo.vue')['default']
    TenantUserInfoPop: typeof import('./src/components/tenant/TenantUserInfoPop.vue')['default']
    UserAuthInfo: typeof import('./src/components/user/UserAuthInfo.vue')['default']
    UserBasicInfo: typeof import('./src/components/user/UserBasicInfo.vue')['default']
    UserTenantInfo: typeof import('./src/components/user/UserTenantInfo.vue')['default']
  }
}

export {}
